services:
  dotnet10aisamples.api:
    image: dotnet10aisamples.api
    build:
      context: .
      dockerfile: Dotnet10AISamples.Api/Dockerfile

  dotnet10agui.api:
    image: dotnet10agui.api
    build:
      context: .
      dockerfile: Dotnet10AGUI.Api/Dockerfile

